"""
Chorley & Seth (2011), "Dopamine-Signaled Reward Predictions Generated by
Competitive Excitation and Inhibition in a Spiking Neural Network Model"
(Front. Comput. Neurosci. 5:21) -- a reduced-scale reproduction of the central
result: the dopamine response shifts from the reward (US) to the reward-predicting
cue (CS), the hallmark of Schultz's midbrain DA recordings.

WHERE THE MODULATORY SIGNAL COMES FROM. The other rules in snn2 (Florian, Farries
& Fairhall) *consume* a reward/dopamine signal. This model *generates* it, from
circuitry. Two pathways carry a sensory event to the DA neurons:

  fast / excitatory :  SEN -> INT -> DA          (no latency; a fast relay)
  slow / inhibitory :  PFC -> STR -| DA          (100 ms cortical latency)

STR makes inhibitory synapses onto DA, so the DA output is a race between fast
excitation (INT) and delayed inhibition (STR). Both plastic pathways (SEN->INT and
PFC->STR) are shaped by DA-modulated STDP (DA-STDP), and STR excitability is gated
by DA (DA-PSF). The competition, trained over CS->US trials, produces:

  - before training : DA fires to the US only (US->INT is wired strong = "reward")
  - after training  : DA fires to the CS (SEN->INT learned the cue) and NOT to the
                      US (PFC->STR learned to fire a precisely-timed inhibition that
                      cancels the still-present INT excitation at US time)
  - unexpected US   : omit the CS -> no anticipatory STR inhibition -> US response
                      REAPPEARS (DA stays sensitive to surprising reward)

HOW LEARNING BOOTSTRAPS (the distal-reward / eligibility mechanism, after
Izhikevich 2007). Plastic synapses are silent at first, so the cue cannot drive
its targets directly. Background firing supplies the exploratory post-synaptic
spikes: when SEN-CS fires at the cue, some INT-CS neurons fire shortly after by
chance, leaving an eligibility trace (gamma); the later US-driven DA burst raises
extracellular DA (alpha) and converts that eligibility into a weight increase
(dw/dt = alpha * gamma). Trial by trial the cue's pathway strengthens. The STR
pathway is made eligible at US time by DA-PSF (a DA burst transiently raises STR
excitability so STR fires just after the burst, tagging the PFC inputs active then).

SCALE. This is a faithful reimplementation of the *mechanism* at reduced size
(tens of neurons per group, short per-trial windows) so it runs in seconds, not
the paper's ~1400 neurons over 1000 s of simulated time. Equations and parameters
are taken from the paper (Materials and Methods); see docs/chorley_seth.md.

Run: python -m snn2.chorley_seth
"""
from __future__ import annotations
import numpy as np


# --------------------------------------------------------------------------- #
# Parameters (from the paper, except group sizes / afferent counts, reduced)
# --------------------------------------------------------------------------- #
P = dict(
    # group sizes (paper: SEN100 INT100 PFC1000 STR100 DA100)
    n_sen=40, n_int=40, n_pfc=120, n_str=40, n_da=40,   # SEN/INT split half US/half CS
    aff=12,                       # afferents per post-synaptic neuron (paper: 100)
    # Izhikevich RS
    izhi_a=0.02, izhi_b=0.2, izhi_c=-65.0, izhi_d=8.0,
    # fixed synapses
    w_int_da=3.0, w_str_da=14.0,   # INT->DA excitatory; STR->DA inhibitory (neg sign)
    w_max=10.0,                   # plastic weight ceiling
    # STDP / eligibility (paper)
    A_plus=0.1, A_minus=0.15, tau_stdp=20.0,            # ms
    tau_gamma_pfc=80.0, tau_gamma_sen=1000.0,          # ms
    # dopamine
    da_step=0.05, tau_alpha=100.0,                      # alpha += 0.05 per DA spike
    alpha_baseline=0.6,
    lr=0.2,                    # scales dw = lr * alpha * gamma (tuning knob)
    # DA-PSF: STR b rises with alpha
    psf_gain=0.05, b_str_max=0.27,
    # background drive (tuned for a few Hz)
    bg_mean=1.2, bg_std=2.5,
    # protocol
    t_cs=200, t_us=700, t_end=1400,   # ms within a trial
    stim_dur=10, stim_amp=12.0,       # SEN stimulus current pulse
    pfc_latency=100, pfc_dur=1000,    # PFC pattern: starts stim+latency, lasts 1 s
    pfc_amp=7.0,
)


def _sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))


# --------------------------------------------------------------------------- #
# Network construction
# --------------------------------------------------------------------------- #
def build(p, seed=0):
    rng = np.random.default_rng(seed)
    nS, nI, nP, nR, nD = p["n_sen"], p["n_int"], p["n_pfc"], p["n_str"], p["n_da"]
    hS, hI, hP = nS // 2, nI // 2, nP // 2          # US half | CS half

    def conn(n_pre, n_post, aff, lo=None, hi=None):
        """post x pre binary mask: each post gets `aff` random afferents."""
        M = np.zeros((n_post, n_pre))
        rows = range(n_post)
        for j in rows:
            src = rng.choice(np.arange(lo or 0, hi or n_pre),
                             size=min(aff, (hi or n_pre) - (lo or 0)), replace=False)
            M[j, src] = 1.0
        return M

    # SEN->INT parallel: US-SEN -> US-INT, CS-SEN -> CS-INT (stimulus regions kept)
    m_si = np.zeros((nI, nS))
    m_si[:hI, :hS] = conn(hS, hI, p["aff"])                 # US block
    m_si[hI:, hS:] = conn(hS, hI, p["aff"])                 # CS block
    # PFC->STR sparse
    m_ps = conn(nP, nR, p["aff"])
    # INT->DA all-to-all-ish (fixed excit), STR->DA (fixed inhib)
    m_id = conn(nI, nD, p["aff"])
    m_rd = conn(nR, nD, p["aff"])

    # plastic weights
    w_si = np.zeros((nI, nS)); w_ps = np.zeros((nR, nP))
    # init: US-SEN -> US-INT at MAX (intrinsic reward); everything else min (0)
    w_si[:hI, :hS] = m_si[:hI, :hS] * p["w_max"]
    return dict(rng=rng, hS=hS, hI=hI, hP=hP,
                m_si=m_si, m_ps=m_ps, m_id=m_id, m_rd=m_rd,
                w_si=w_si, w_ps=w_ps)


def pfc_pattern(p, net, which, seed):
    """Pre-computed sustained 1 s PFC current pattern for a stimulus (US/CS).
    Drawn from the same background distribution -> no rate change, only a fixed
    spatio-temporal pattern (the polychronous substrate)."""
    rng = np.random.default_rng(seed)
    nP, hP, dur = p["n_pfc"], net["hP"], p["pfc_dur"]
    C = np.zeros((dur, nP))
    cols = np.arange(0, hP) if which == "US" else np.arange(hP, nP)
    C[:, cols] = p["pfc_amp"] * (rng.random((dur, len(cols))) < 0.5)
    return C


# --------------------------------------------------------------------------- #
# One trial
# --------------------------------------------------------------------------- #
def run_trial(p, net, pfc_cs, pfc_us, present_cs=True, present_us=True,
              learn=True, state=None):
    rng = net["rng"]
    nS, nI, nP, nR, nD = p["n_sen"], p["n_int"], p["n_pfc"], p["n_str"], p["n_da"]
    hS, hI, hP = net["hS"], net["hI"], net["hP"]
    a, b0, c, d = p["izhi_a"], p["izhi_b"], p["izhi_c"], p["izhi_d"]

    def mk(n): return np.full(n, c), b0 * np.full(n, c)
    vS, uS = mk(nS); vI, uI = mk(nI); vP, uP = mk(nP); vR, uR = mk(nR); vD, uD = mk(nD)

    # plasticity traces
    if state is None:
        state = {}
    alpha = state.get("alpha", p["alpha_baseline"])
    g_si = state.get("g_si", np.zeros_like(net["w_si"]))   # eligibility SEN->INT
    g_ps = state.get("g_ps", np.zeros_like(net["w_ps"]))   # eligibility PFC->STR
    # STDP traces (pre/post exponential)
    xpre_S = np.zeros(nS); ypost_I = np.zeros(nI)
    xpre_P = np.zeros(nP); ypost_R = np.zeros(nR)

    w_si, w_ps = net["w_si"], net["w_ps"]
    m_id, m_rd = net["m_id"], net["m_rd"]
    da_raster = np.zeros(p["t_end"])
    str_raster = np.zeros(p["t_end"])
    dec_stdp = np.exp(-1.0 / p["tau_stdp"])
    dec_a = np.exp(-1.0 / p["tau_alpha"])
    dec_gs = np.exp(-1.0 / p["tau_gamma_sen"])
    dec_gp = np.exp(-1.0 / p["tau_gamma_pfc"])

    # previous-step spikes (1 ms synaptic delay)
    sS = np.zeros(nS); sI = np.zeros(nI); sP = np.zeros(nP); sR = np.zeros(nR); sD = np.zeros(nD)

    for t in range(p["t_end"]):
        # ---- external / stimulus currents -------------------------------- #
        xiS = rng.normal(p["bg_mean"], p["bg_std"], nS)
        xiI = rng.normal(p["bg_mean"], p["bg_std"], nI)
        xiP = rng.normal(p["bg_mean"], p["bg_std"], nP)
        xiR = rng.normal(p["bg_mean"], p["bg_std"], nR)
        xiD = rng.normal(p["bg_mean"], p["bg_std"], nD)

        # SEN stimulus pulses (transient firing-rate bump on the stimulus half)
        if present_cs and p["t_cs"] <= t < p["t_cs"] + p["stim_dur"]:
            xiS[hS:] += p["stim_amp"]                          # CS-SEN
        if present_us and p["t_us"] <= t < p["t_us"] + p["stim_dur"]:
            xiS[:hS] += p["stim_amp"]                          # US-SEN
        # PFC sustained patterns (replace background on the stimulus half)
        if present_cs:
            tt = t - (p["t_cs"] + p["pfc_latency"])
            if 0 <= tt < p["pfc_dur"]:
                xiP[hP:] = pfc_cs[tt, hP:]
        if present_us:
            tt = t - (p["t_us"] + p["pfc_latency"])
            if 0 <= tt < p["pfc_dur"]:
                xiP[:hP] = pfc_us[tt, :hP]

        # ---- synaptic currents (from previous-step spikes) --------------- #
        I_I = (w_si * net["m_si"]) @ sS + xiI
        I_P = xiP
        I_R = (w_ps * net["m_ps"]) @ sP + xiR
        I_D = p["w_int_da"] * (m_id @ sI) - p["w_str_da"] * (m_rd @ sR) + xiD
        I_S = xiS

        # DA-PSF: alpha raises STR excitability (parameter b)
        b_str = min(p["b_str_max"], b0 + p["psf_gain"] * max(0.0, alpha - p["alpha_baseline"]))

        # ---- Izhikevich updates (two 0.5 ms substeps for v) -------------- #
        def step(v, u, I, bb):
            for _ in range(2):
                v = v + 0.5 * (0.04 * v * v + 5 * v + 140 - u + I)
            u = u + a * (bb * v - u)
            fired = v >= 30.0
            v = np.where(fired, c, v); u = np.where(fired, u + d, u)
            return v, u, fired.astype(np.float64)

        vS, uS, fS = step(vS, uS, I_S, b0)
        vI, uI, fI = step(vI, uI, I_I, b0)
        vP, uP, fP = step(vP, uP, I_P, b0)
        vR, uR, fR = step(vR, uR, I_R, b_str)
        vD, uD, fD = step(vD, uD, I_D, b0)

        da_raster[t] = fD.sum(); str_raster[t] = fR.sum()

        # ---- dopamine concentration -------------------------------------- #
        alpha = alpha * dec_a + p["da_step"] * fD.sum()

        # ---- STDP eligibility (trace-based) ------------------------------ #
        if learn:
            xpre_S = xpre_S * dec_stdp + fS
            ypost_I = ypost_I * dec_stdp + fI
            xpre_P = xpre_P * dec_stdp + fP
            ypost_R = ypost_R * dec_stdp + fR
            # SEN->INT: LTP on INT post-spike, LTD on SEN pre-spike
            g_si = g_si * dec_gs
            g_si += p["A_plus"] * np.outer(fI, xpre_S) * net["m_si"]
            g_si -= p["A_minus"] * np.outer(ypost_I, fS) * net["m_si"]
            # PFC->STR
            g_ps = g_ps * dec_gp
            g_ps += p["A_plus"] * np.outer(fR, xpre_P) * net["m_ps"]
            g_ps -= p["A_minus"] * np.outer(ypost_R, fP) * net["m_ps"]
            # DA-STDP: dw = lr * alpha * gamma
            w_si += p["lr"] * alpha * g_si
            w_ps += p["lr"] * alpha * g_ps
            np.clip(w_si, 0, p["w_max"], out=w_si)
            np.clip(w_ps, 0, p["w_max"], out=w_ps)

        sS, sI, sP, sR, sD = fS, fI, fP, fR, fD

    return {"da": da_raster, "str": str_raster,
            "state": {"alpha": p["alpha_baseline"]}}   # reset alpha between trials


# --------------------------------------------------------------------------- #
# Experiments
# --------------------------------------------------------------------------- #
def _da_response(raster, t0, win=(0, 150)):
    """DA spike count in [t0+win0, t0+win1)."""
    return raster[t0 + win[0]: t0 + win[1]].sum()


def train(p=None, n_trials=100, seed=0, record_every=1):
    p = dict(P, **(p or {}))
    net = build(p, seed)
    pfc_cs = pfc_pattern(p, net, "CS", seed + 1)
    pfc_us = pfc_pattern(p, net, "US", seed + 2)
    cs_resp, us_resp, str_pre, rasters = [], [], [], {}
    for k in range(n_trials):
        out = run_trial(p, net, pfc_cs, pfc_us, True, True, learn=True)
        cs_resp.append(_da_response(out["da"], p["t_cs"]))
        us_resp.append(_da_response(out["da"], p["t_us"]))
        str_pre.append(out["str"][p["t_us"] - 150:p["t_us"] + 20].sum())
        if k in (0, n_trials // 2, n_trials - 1):
            rasters[k] = out
    return dict(net=net, p=p, pfc_cs=pfc_cs, pfc_us=pfc_us,
                cs=np.array(cs_resp), us=np.array(us_resp),
                str_pre=np.array(str_pre), rasters=rasters)


def probe(trained, present_cs=True, present_us=True, n=10):
    """Average DA (and STR) raster over n frozen (no-learning) trials."""
    p, net = trained["p"], trained["net"]
    da = np.zeros(p["t_end"]); st = np.zeros(p["t_end"])
    for _ in range(n):
        out = run_trial(p, net, trained["pfc_cs"], trained["pfc_us"],
                        present_cs, present_us, learn=False)
        da += out["da"]; st += out["str"]
    return da / n, st / n


# --------------------------------------------------------------------------- #
# Validation
# --------------------------------------------------------------------------- #
def validate(n_trials=100, seed=0, verbose=True):
    log = print if verbose else (lambda *a, **k: None)
    tr = train(n_trials=n_trials, seed=seed)
    p = tr["p"]
    cs, us, str_pre = tr["cs"], tr["us"], tr["str_pre"]

    pre_cs, pre_us = cs[:5].mean(), us[:5].mean()
    post_cs, post_us = cs[-10:].mean(), us[-10:].mean()
    str_growth = str_pre[-10:].mean() - str_pre[:5].mean()
    us_suppress = 100 * (1 - post_us / max(pre_us, 1e-9))

    da_full, _ = probe(tr, True, True, n=12)
    da_omit_cs, _ = probe(tr, False, True, n=12)
    us_predicted = _da_response(da_full, p["t_us"])
    us_unexpected = _da_response(da_omit_cs, p["t_us"])

    log("Chorley & Seth (2011) -- dopamine US->CS shift (reduced-scale)\n")
    log("DA response (spikes in 150 ms post-stimulus):")
    log("  before training : CS=%5.1f  US=%5.1f" % (pre_cs, pre_us))
    log("  after  training : CS=%5.1f  US=%5.1f  (US suppressed %.0f%%)"
        % (post_cs, post_us, us_suppress))
    log("  anticipatory STR firing near US, growth over training: %+.1f" % str_growth)
    log("  unexpected US (CS omitted): US=%.1f  vs predicted US=%.1f"
        % (us_unexpected, us_predicted))

    checks = [
        ("before training DA responds to US, not CS (US > 2*CS)",
         pre_us > 2 * max(pre_cs, 0.5)),
        ("DA response to the CS emerges with training (post_cs > pre_cs + 8)",
         post_cs > pre_cs + 8),
        ("after training DA responds strongly to the CS (post_cs > 2*pre_cs)",
         post_cs > 2 * max(pre_cs, 0.5)),
        ("the inhibitory pathway develops anticipatory STR firing (growth > 5)",
         str_growth > 5),
        ("the US response is suppressed relative to before (post_us < pre_us)",
         post_us < pre_us),
        ("omitting the CS does not reduce the US response (unexpected >= predicted)",
         us_unexpected >= us_predicted - 1),
    ]
    log("\nValidation:")
    for name, ok in checks:
        log("  [%s] %s" % ("PASS" if ok else "FAIL", name))
    passed = all(ok for _, ok in checks)
    log("\n%s" % ("ALL CHECKS PASSED" if passed else "SOME CHECKS FAILED"))
    log("\nNote: the CS-response shift is robust; full *cancellation* of the US\n"
        "response needs the paper's larger polychronous substrate (here it is\n"
        "partial -- see docs/chorley_seth.md).")
    return {"checks_passed": passed, "cs": cs, "us": us, "str_pre": str_pre,
            "pre_cs": pre_cs, "pre_us": pre_us, "post_cs": post_cs,
            "post_us": post_us, "us_suppress": us_suppress,
            "str_growth": str_growth, "us_unexpected": us_unexpected,
            "us_predicted": us_predicted, "trained": tr}


# --------------------------------------------------------------------------- #
# Figure
# --------------------------------------------------------------------------- #
def make_figure(path="chorley_seth_fig.png", n_trials=100, seed=0):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    tr = train(n_trials=n_trials, seed=seed)
    p = tr["p"]
    da_post, st_post = probe(tr, True, True, n=15)
    da_pre, st_pre = probe_first(tr)

    fig, axes = plt.subplots(1, 3, figsize=(14, 4.3))

    # (A) the shift: CS and US response trajectories
    ax = axes[0]
    sm = lambda a: np.convolve(a, np.ones(6) / 6, mode="valid")
    ax.plot(sm(tr["cs"]), color="#16a34a", lw=2, label="CS response")
    ax.plot(sm(tr["us"]), color="#dc2626", lw=2, label="US response")
    ax.set_title("DA response shifts toward the cue", fontsize=11)
    ax.set_xlabel("conditioning trial"); ax.set_ylabel("DA spikes (150 ms)")
    ax.legend(fontsize=9)

    # (B) peri-event DA, before vs after
    ax = axes[1]
    binw = 20
    def hist(r):
        n = (len(r) // binw) * binw
        return r[:n].reshape(-1, binw).sum(1)
    t = (np.arange(len(hist(da_pre))) * binw - p["t_cs"])
    ax.plot(t, hist(da_pre), color="#9ca3af", lw=2, label="before training")
    ax.plot(t, hist(da_post), color="#111827", lw=2, label="after training")
    ax.axvline(0, color="#16a34a", ls=":", lw=1.2)
    ax.axvline(p["t_us"] - p["t_cs"], color="#dc2626", ls=":", lw=1.2)
    ax.text(5, ax.get_ylim()[1] * 0.92, "CS", color="#16a34a", fontsize=9)
    ax.text(p["t_us"] - p["t_cs"] + 5, ax.get_ylim()[1] * 0.92, "US",
            color="#dc2626", fontsize=9)
    ax.set_title("DA peri-event histogram\n(US-driven, then CS-driven)", fontsize=11)
    ax.set_xlabel("time from CS (ms)"); ax.set_ylabel("DA spikes / 20 ms")
    ax.legend(fontsize=9)

    # (C) anticipatory STR inhibition develops
    ax = axes[2]
    ax.plot(sm(tr["str_pre"]), color="#7c3aed", lw=2)
    ax.set_title("Inhibitory pathway:\nanticipatory STR firing near US", fontsize=11)
    ax.set_xlabel("conditioning trial")
    ax.set_ylabel("STR spikes in [US-150, US+20] ms")

    fig.suptitle("snn2 — Chorley & Seth (2011): a dual-pathway circuit generates "
                 "the dopamine reward-prediction signal", fontsize=12.5, y=1.02)
    fig.tight_layout()
    fig.savefig(path, dpi=130, bbox_inches="tight")
    plt.close(fig)
    return path


def probe_first(tr):
    """DA/STR raster from a fresh, untrained copy of the network."""
    p = tr["p"]
    net0 = build(p, 0)
    da = np.zeros(p["t_end"]); st = np.zeros(p["t_end"])
    for _ in range(15):
        out = run_trial(p, net0, tr["pfc_cs"], tr["pfc_us"], True, True, learn=False)
        da += out["da"]; st += out["str"]
    return da / 15, st / 15


def probe_from_raster(tr, key):
    out = tr["rasters"][key]
    return out["da"], out["str"]


def main():
    print("Validating Chorley & Seth (2011) reproduction:\n")
    validate()


if __name__ == "__main__":
    main()
